### ISSUE TITLE
`Includes` don't support big string

### ISSUE THREAD

**Issue by Manu1400** [harrysolovay/ts-stl-std#2]
Testcase : 
https://www.typescriptlang.org/play?ts=4.1.0-beta#code/C4TwDgpgBAkgdgYwDYFcAmEDOAeAygJwSggA9gI41MpNh8BLOAcwBopcIBDQgC2LIpUadRkwB8UALztC-cpWoADACQBvDtwQ8AvmsYAzCPigB9AEpZg2xQCgoUAPxQ6KCHagAuGUVLyhK1QMjUwBhAAZdQLhDYwtaa3d7JzjgOUFqACIMxPtHKH1OJEw3XNyveGR0LGwUtg1eMRyvOAgANyMAbhsbAHoeqAAVcGhGWk44YHpOSYB7OCh6alIELEx6dqQQKAwIMChxtCgwGcw1gCNNhejGenIAOgAKACYAVgAOAE4AShtQSEHLAhOMUpLBEKgMDgMgBGJ4AZgALC8AGwAdk+YVhiJR6I+mPhCKxSLRGKJONJBIybAyUAyjSAA

=> `Type instantiation is excessively deep and possibly infinite.(2589)`

**Comment by harrysolovay** [comment]
Yes––it is unfortunate. Hopefully longer strings will be supported in future version of TS.
